### ISSUE TITLE
Where are the TDWG Ontologies going to go?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/infrastructure#33]
The TDWG Ontologies are currently residing at https://code.google.com/p/tdwg-ontology/ which will be shut down in the near future.  Sections 2.4 and 2.6.1 of the [VoMaG Report](https://github.com/tdwg/vocab/blob/master/gbif_TDWG_Vocabulary_Management_Task_Group_en_v1.0.pdf) are devoted to discussion and recommendations regarding the fate of the TDWG ontologies.  The recommendations related to the TDWG Ontologies in the VoMaG Report were discussed at the 2013 TDWG meeting in Florence and by my recollection, there was a consensus that they should be implemented.  However, I don't think any action was ever actually taken on those recommendations.  This would be an optimal time to take care of this matter.  

Given that the TDWG Ontologies are unmaintained and effectively deprecated, the primary task is to archive them somewhere.  That could be easily achieved in the current effort to archive materials at this GitHub site.  I am going to list some action items below with reference to specific recommendations of the VoMaG Report.  I don't think we need any additional approval to take these actions since the Ontologies aren't governed by the Standards Process and they've already been hashed out in the report and at the annual meeting.  
1. Create a repository for the TDWG Ontologies.  They don't have any status as standards, so they really don't belong in the prior standards repo.  In the README for the repository, indicate that the Ontologies are no longer under development.  (Recommendation 2.1.).
2. Create a frozen version of the existing files using the same mechanisms used for old versions of the standards.  The master version of the files should be modified as described in the following items.
3. The files TaxonConcept.owl, TaxonName.owl, and TaxonRank.owl should be marked as deprecated using the syntax shown in Recommendation 2.4.
4. Remove the XSL stylesheet code from all of the documents.  These are machine-readable documents and this stylesheet is not appropriate for the reasons given in Recommendation 2.5.
5. Indicate that the ontology documents that are mentioned in Recommendation 2.8 are deprecated, using the syntax described in Rec 2.8.  
6. Remove subclass declarations as described in Recommendation 2.9.
7. Increment the version number by 0.1 on all files that were edited, update the modified date, and indicate the nature of the modification. (Recommendation 2.7)
8. Set up redirects from http://rs.tdwg.org/ontology2/ and http://rs.tdwg.org/ontology/ so that they point to the modified files in the master folder.

Taking these actions will fulfill most of the recommendations in the VoMaG Report related to the TDWG Ontologies.  @peterdesmet can you set up the repo, create the frozen release in the same manner as you've done for old versions of standards and put copies of all of the files currently in  the trunk/ontology folder and voc subfolder of the https://code.google.com/p/tdwg-ontology/ into the master of the repo?  If you do that and give me editing privileges, I can make the required edits to the files in the master and the README. 

/cc @tdwg/exec

**Comment by jmacklin** [comment]
I agree with Steve that now is a good time to accomplish this while we are at it assuming our very generous migrators can spare the time. His list of action items seem reasonable.

Thanks also to Steve for being proactive and offering to help out :-)

Best,  JAmes

**Comment by mdoering** [comment]
+1 Steve. @peterdesmet if you need help with migration let me know. In any case please already create the repo & team. And again we will need to patch the rewrite rules for [rs.tdwg.org](https://github.com/tdwg/infrastructure/blob/master/vhosts/rs.tdwg.org.conf#L117), see https://github.com/tdwg/infrastructure/issues/4. Ill create an issue once the new repo exists

**Comment by peterdesmet** [comment]
Ok! Since everything is TDWG, I've named the repo and group `ontology`, not `tdwg-ontology`: https://github.com/tdwg/ontology. @mdoering, you're now member of the team.

Since all info is on Google Code, a migrator script should be used to transfer files, commit history and issues, which is also why I didn't initialize the repository with a README. @mdoering, would you be able to migrate?

Also, I don't think the @tdwg/exec mentioned worked in Steve's description, which I why I'm adding them here. Exec, Steve wants you to be notified of this issue: https://github.com/tdwg/infrastructure/issues/33

**Comment by mdoering** [comment]
I have migrated the google code svn to the github repo. There was a tag for the latest version already created by tuco in 2009 so I did not create another one.

**Comment by mdoering** [comment]
@baskaufs I have added you to the ontology team. Could you create individual issues in the ontology repository for the refactoring tasks you listed at the start of this issue?

**Comment by baskaufs** [comment]
Yes,thanks.   I'm on it.

**Comment by CynthiaParr-USDA** [comment]
Is this issue assigned to anybody? Is there anything left to do?

**Comment by mdoering** [comment]
The remaining issues are listed in the ontology repo. I have created a milestone to group all issues left to do before the ontology github migration can be considered completed:
https://github.com/tdwg/ontology/milestones/Github%20migration

**Comment by baskaufs** [comment]
I started on editing the documents but ran out of time before I went on vacation.  I'm back onto it now, see https://github.com/tdwg/ontology/issues/10 @mdoering @csparr

**Comment by ctsakem** [comment]
sorry to my matest reaction due to the bad internet network connetion in my city.I I be able to migrate 
thank
 TSAKEM Samuel Christian 
Enseignant/Chercheur
Chef Services des Etudes et Stages
Ecole de Faune de Garoua
BP : 271 Garoua-Cameroon
Tél: 00237-97692181,  Bureau: 22271838 Domicile: 22846955Email: ctsakem@yahoo.fr, Skype: ctsakem http://clone.concordia.ca/rweladji/students/Samuel.html     

```
 Le Vendredi 5 juin 2015 9h19, Peter Desmet <notifications@github.com> a écrit :
```

 Ok! Since everything is TDWG, I've named the repo and group ontology, not tdwg-ontology: https://github.com/tdwg/ontology. @mdoering, you're now member of the team.Since all info is on Google Code, a migrator script should be used to transfer files, commit history and issues, which is also why I didn't initialize the repository with a README. @mdoering, would you be able to migrate?Also, I don't think the @tdwg/exec mentioned worked in Steve's description, which I why I'm adding them here. Exec, Steve wants you to be notified of this issue: #33—
