### ISSUE TITLE
Fix problems with accessing old proceedings from OJS

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#44]
I think these are in OJS and that's why they are currently inaccessible. I thought the plan was to keep a PDF or something so that even if they are not interactive they can still be read.

I was looking for an abstract yesterday from 2009 and links led me to a dead Typo3 link.
From Google:
Volk, Gayle, USDA ARS - TDWG
www.tdwg.org/.../view?...Vol...
Biodiversity Information Standards TDWG
Volk, Gayle USDA ARS. 2009 - Identifying Biodiversity for Food and Agriculture Data integration and its impact on genebank management. Abstract.

The link is to http://www.tdwg.org/proceedings/search/authors/view?firstName=Gayle&middleName=&lastName=Volk&affiliation=USDA%20ARS and the typo3 error I get is:

Page Not Found

Reason: Segment "proceedings" was not a keyword for a postVarSet as expected on page with id=157.

I'm guessing that this particular link may not be fixable but I wasn't able to get to the abstract any other way, and that may be fixable.

**Comment by gkampmeier** [comment]
Given that when we were using the Proceedings as peer-reviewed abstracts, I would be many people used specific links in their cvs to point to these. Would a longer-term solution be to seek DOIs and/or work with BHL (and BioStor?) to give these more permanent links?

Gail

http://www.inhs.illinois.edu/~gkamp

On Aug 7, 2015, at 7:41 AM, Cyndy Sims Parr <notifications@github.com<mailto:notifications@github.com>> wrote:

I think these are in OJS and that's why they are currently inaccessible. I thought the plan was to keep a PDF or something so that even if they are not interactive they can still be read.

I was looking for an abstract yesterday from 2009 and links led me to a dead Typo3 link.
From Google:
Volk, Gayle, USDA ARS - TDWG
www.tdwg.org/.../view?...Volhttps://urldefense.proofpoint.com/v2/url?u=http-3A__www.tdwg.org_..._view-3F...Vol&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=dcUvap8p35KB6gSuuAeNKiPFUQTLzBHzu-nrsIqoCsI&m=IUKy8GkPFkqwmepQ9iAMzLcK44g7IvgVrjPzoVIcVgQ&s=kAPMUuT-f85fPBe0E7rguKHvcjdvO-ZKqwBcQKQsrN4&e=...
Biodiversity Information Standards TDWG
Volk, Gayle USDA ARS. 2009 - Identifying Biodiversity for Food and Agriculture Data integration and its impact on genebank management. Abstract.

The link is to http://www.tdwg.org/proceedings/search/authors/view?firstName=Gayle&middleName=&lastName=Volk&affiliation=USDA%20ARShttps://urldefense.proofpoint.com/v2/url?u=http-3A__www.tdwg.org_proceedings_search_authors_view-3FfirstName-3DGayle-26middleName-3D-26lastName-3DVolk-26affiliation-3DUSDA-2520ARS&d=AwMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=dcUvap8p35KB6gSuuAeNKiPFUQTLzBHzu-nrsIqoCsI&m=IUKy8GkPFkqwmepQ9iAMzLcK44g7IvgVrjPzoVIcVgQ&s=IvN0BHPvJNvJt94JAiCnRgsHuTi_CBVPV-2ZO3xb_ec&e= and the typo3 error I get is:

Page Not Found

Reason: Segment "proceedings" was not a keyword for a postVarSet as expected on page with id=157.

I'm guessing that this particular link may not be fixable but I wasn't able to get to the abstract any other way, and that may be fixable.

**Comment by CynthiaParr-USDA** [comment]
I am not sure if it really blocks server shutdown but want to ensure that it does not and then assign to someone to deal with it.

**Comment by CynthiaParr-USDA** [comment]
@stanblum can you comment on the location of the old OJS abstracts?  Have they been saved? Are they on the server we want to shut down.

**Comment by CynthiaParr-USDA** [comment]
These exist in the Wayback machine. https://web.archive.org/web/20070630140549/http://www.tdwg.org/ojs/

**Comment by CynthiaParr-USDA** [comment]
Stan, can you figure out a plan to make the content accessible again for the proceedings?  It looks to me like it was only one year.

**Comment by stanblum** [comment]
I've got html and PDFs for 2006, 2007, 2008, and 2009.  I'm going to post
at least the PDFs on www.tdwg.org (actually they'r already there, just need
to be exposed).  I will see what happens with the html.

These will be all abstracts in a single doc/page.

**Comment by stanblum** [comment]
I've linked the PDFs for the proceedings -- all abstracts in one file -- and there are now linked under 

http://www.tdwg.org/proceedings 

I might try to post some html versions, but I think that's a lower priority, so I'm going to close this.
