### ISSUE TITLE
All standards pages redirect to standards overview

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/infrastructure#46]
I discovered a problem on the standards page (http://www.tdwg.org/standards/, which I'm in the process of updating). If you click any of the standards, you get shown the same overview page, instead of the standard (cover) page (try with http://www.tdwg.org/standards/115/). That means the standard pages are currently unreachable. This is probably due to the migration, as it's still working fine on ww1.

There are two standards that are reachable and both are also shown in the menu (which wasn't the case before):
- GUID: with the correct working URL: http://www.tdwg.org/standards/150
- DwC: with the working, but incorrect URL: http://tdwgng.tdwg.org/standards/dwc/ (should actually be http://www.tdwg.org/standards/450)

Note that this is a temporary problem, as eventually all those URLs ending with a number, will redirect to a specific GitHub repository (@mdoering, will this be done in Apache or Typo3?). We can already do this for some standards, but not all are ready yet. In any case, I'm curious why those pages weren't migrated (I also can't see them in the Typo3 backend).

**Comment by peterdesmet** [comment]
Just updated the standards page to one table: http://www.tdwg.org/standards/ The problem remains, and since I updated the URL for Darwin Core to permanent http://www.tdwg.org/standards/450, that one no longer works either.

**Comment by CynthiaParr-USDA** [comment]
I have been thinking about this. It may be that we didn't port the standards pages over because they were now set up at GitHub? No, they aren't the same. Were they on the tdwgng.tdwg.org site?

 Until the redirects are ready, perhaps we should point to the old pages at http://ww1.tdwg.org/standards/xxx.

I just changed TAPIR to that ww1 address and that works -- that's not ideal as the "permanent URL" shown in those pages has also changed to the ww1 site address.  

Stan may not be reachable for a bit -- he said something about travel. Perhaps ask Tim/Markus/Cip/Andreas about the redirects.

**Comment by mdoering** [comment]
Hi cyndy, instead of working on intermediate solutions lets set up theredirects instead. I will give it a try in a few hours, we just need to make sure all standards are covered. Do all have a github page yet? The redirect #issue4 lists these redirects: https://github.com/tdwg/infrastructure/blob/master/migration/redirects.csv

I have added a [www.tdwg.org vhost](https://github.com/tdwg/infrastructure/blob/master/vhosts/www.tdwg.org.conf) and deployed that to the servers. If anything needs to be changed or added please do this in that file from now on.

**Comment by mdoering** [comment]
Most standards redirect now, there are just a few broken ones still: 
- 107 Delta
- 117 TCS
- 312 NCD
- tapir: link is wrong and points to ww1.tdwg.org

**Comment by peterdesmet** [comment]
Thanks @mdoering, works now for all except the 3 that don't have a repo yet. I also removed DwC and GUID from the side menu. Closing this issue.

**Comment by CynthiaParr-USDA** [comment]
Thanks guys for the fantastic progress.
