### ISSUE TITLE
Create special page for the JRS acknowledgement`

### ISSUE THREAD

**Issue by CynthiaParr-USDA** [tdwg/infrastructure#50]
They have a long history of support and deserve extra recognition. Should get a logo and some text.

**Comment by pmergen** [comment]
have contacted Hank Bart to coordinate with him for a text. We have their logo from previous years

**Comment by CynthiaParr-USDA** [comment]
In my notes from August XC meeting we said that Stan would post this (and ackknowledge other sponsors of the meeting -- which needs to come from Lucy) so I am assigning to Stan.

**Comment by pmergen** [comment]
yes there are actually two things here 
- the acknowledgement of the sponsors for this year conference
- the JRS who's president indicated that they would be happy to see a dedicated page thanking them for their support during the last five years or so .. independent from a specific conference
  I had contacted @HankBart for the second item as he has more info as to when their support first started and how much and what they sponsored over the years so we can thank them properly and highlight some of their sponsored activities on this page. I have some group pictures of JRS participants that could be used.

**Comment by CynthiaParr-USDA** [comment]
Stan, this is a task that is still waiting. Would be good to do it soon in case we are thinking of applying for travel funds from them.

**Comment by stanblum** [comment]
Cyndy, et al.,   how is this?

http://www.tdwg.org/acknowledgements

This page can be viewed by anyone with the link.  At the moment, I have it
placed in the navigation tree (as "Acknowledgements") just after "Past
Meetings".   We can move it easily if another location is more
appropriate.  And we can unhide it in the navigation tree as soon as the
page is approved.  We can also put a link to this page at the bottom of the
home page as a separate text item, not as part of the footer.
Unfortunately, I still haven't figured out where the controls are for the
page footer.  Still looking...

William said he thinks he found the footer control, but it hasn't worked yet.  I'll talk to him and see if we can figure it out.  Will update status with those results.

**Comment by CynthiaParr-USDA** [comment]
Sorry, I missed this. Too much github traffic from all my projects!

The page seems oddly crowded and/or text heavy. Maybe include an image from Hank showing the awardees last year?

**Comment by stanblum** [comment]
I agree about the crowding.  I might have to change the types of the page elements to get it to open up.  I'll ask Hank for a picture if it isn't already posted somewhere.

**Comment by WUlate** [comment]
Footer is modified...

The TDWG Page footer is the page.10.subparts.pageFooter.value within the TDWG Website Template at the HomePage.

To edit it in Typo3 click the Template option below the WEB tree root. 
Then click the HomePage in the TDWG - Production/Staging tree and 
choose(click) the TDWG Website Template (it's at the bottom of the list).  
Then choose the TypoScript Object Browser in the listbox menu on top (the one with Constant Editor, Info/Modify and Template Analyzer).  

While showing the TDWG Website Template, choose to Browse the Setup Root and open the tree path: 
.....[page]
..........[10]
...............[subparts]
....................[pageFooter] 
.........................[value]

Click on [value].

Current value is:

`<p><a rel="license" href="http://creativecommons.org/licenses/by/3.0/us/">   <img alt="Creative Commons License" id="creative_commons_icon" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a>     Copyright 2007 - Biodiversity Information Standards - TDWG - <a href="http://www.tdwg.org/about-tdwg/contact-us/">Contact Us</a><br/> <p>Except where otherwise noted, content on this site is licensed under a     <a rel="license" href="http://creativecommons.org/licenses/by/3.0/us/">             Creative Commons Attribution 3.0 United States License</a>.</p>   <p>Hosted by <a href="http://www.gbif.org">GBIF</a> and <a href="http://www.nhm.ac.uk/">The NHM</a> -      Design by <a href="http://www.ultimedia.com.au" target="_blank">Ultimedia</a></p>    <p><a href="http://www.moore.org"><img src="/fileadmin/template/main/tdwg01/images/moore_logo.jpg" alt="The Gordon and Betty Moore Foundation"/></a>&nbsp;     <a href="http://validator.w3.org/check?uri=referer"><img src="http://www.w3.org/Icons/valid-xhtml10"         alt="Valid XHTML 1.0 Transitional" height="31" width="88" /></a>&nbsp;     <a href="http://www.tdwg.org/acknowledgements"><img src="http://www.tdwg.org/fileadmin/logos/external/JRS_Logo-01.png"           alt="JRS Acknowledgement" /></a>&nbsp;  </p>`

**Comment by CynthiaParr-USDA** [comment]
Can this be closed?

**Comment by WUlate** [comment]
Yes, please, for some reason this allows me to comment but not to close.
